name: mgr
dependencies:
  - python=3.7.16
  - pip=22.3.1
  - pandas=1.3.5
  - pyarrow=8.0.0
  - conda-forge::numpy=1.21.6
  - conda-forge::biopython=1.78
  - bioconda::meme=4.11.2
  - bioconda::pybedtools=0.8.1
  - bioconda::pybigwig=0.3.18
  - lightgbm=3.1.1
  - matplotlib=3.5.3
  - conda-forge::optuna=3.1.1
  - xgboost=1.5.1
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - seaborn=0.12.2
  - pyyaml=6.0
  - tqdm=4.64.1
  - prettytable=3.5.0
  - conda-forge::polars=0.14.23
  - pip:
    - kedro==0.18.8
    - kedro-mlflow==0.11.8
    - kedro-viz==6.1.1