random_state: 42

# negative sampling types
n1: 
  type: anchors_from_other_cell_types
  human_neg_pos_ratio: 0
  human_path_fasta_anchors_with_open_chromtin: data/02_intermediate/Homo_sapiens/n1/n1_anchors_with_open_chromtin.fasta
n2:
  type: new_pairs_of_anchors
  human_neg_pos_ratio: 5
  fly_neg_pos_ratio: 5
  human_path_fasta_anchors_with_open_chromtin: data/02_intermediate/Homo_sapiens/n2/n2_anchors_with_open_chromtin.fasta
  fly_path_fasta_anchors_with_open_chromtin: data/02_intermediate/D_melanogaster/n2/n2_anchors_with_open_chromtin.fasta
n3:
  type: open_chromatin_regions
  human_neg_pos_ratio: 5
  fly_neg_pos_ratio: 5
  human_path_fasta_anchors_with_open_chromtin: data/02_intermediate/Homo_sapiens/n3/n3_anchors_with_open_chromtin.fasta
  fly_path_fasta_anchors_with_open_chromtin: data/02_intermediate/D_melanogaster/n3/n3_anchors_with_open_chromtin.fasta
n4:
  type: FLY_short_loops_as_negatives
  human_neg_pos_ratio: None
  fly_neg_pos_ratio: None
  fly_path_fasta_anchors_with_open_chromtin: data/02_intermediate/D_melanogaster/n4/n4_anchors_with_open_chromtin.fasta